### ISSUE TITLE
examples doesn't work

### ISSUE THREAD

**Issue by alliby** [limikael/appy#22]
i try to run the hello example and the compiler can't find the glapp dependency path
```
❯ cargo r --example hello
error: failed to get `glapp` as a dependency of package `appy v0.1.6 (/home/cargo/Repo/appy)`

Caused by:
  failed to load source for dependency `glapp`

Caused by:
  Unable to update /home/cargo/Repo/glapp

Caused by:
  failed to read `/home/cargo/Repo/glapp/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

```

**Comment by limikael** [comment]
Thanks so much for testing! And thanks for reporting! Please try again now, it should have been fixed!

(the problem was that I had misunderstood the default behaviour when `path:` is specified for dependencies in `Cargo.toml`)
